In [13]:
import pandas as pd

df = pd.read_csv("global_ads_performance_dataset-selected-columns.csv")
df.head()

,date,platform,campaign_type,industry,country,impressions,clicks,CTR,CPC,ad_spend
0,2024-01-21,Google Ads,Search,Fintech,UAE,59886,2113,0.0353,1.26,2662.38
1,2024-01-22,TikTok Ads,Search,EdTech,UK,135608,5220,0.0385,1.18,6159.60
2,2024-06-15,TikTok Ads,Video,Healthcare,USA,92313,5991,0.0649,0.85,5092.35
3,2024-01-02,TikTok Ads,Shopping,SaaS,Germany,83953,5935,0.0707,1.32,7834.20
4,2024-02-22,TikTok Ads,Search,Healthcare,UK,91807,4489,0.0489,1.93,8663.77

In [14]:
print(df.shape)

(1800, 10)

In [25]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values(by='date')

df

           date    platform campaign_type    industry    country  impressions  \
845  2024-01-01  TikTok Ads       Display        SaaS        USA       103026
577  2024-01-01  Google Ads        Search        SaaS      India        21702
355  2024-01-02    Meta Ads         Video      EdTech        USA       138639
3    2024-01-02  TikTok Ads      Shopping        SaaS    Germany        83953
1281 2024-01-02    Meta Ads        Search  Healthcare      India       163624
1621 2024-01-02    Meta Ads       Display        SaaS         UK       143485
1433 2024-01-03    Meta Ads        Search  E-commerce         UK        91392
1042 2024-01-03    Meta Ads       Display     Fintech     Canada       129750
1100 2024-01-03  TikTok Ads        Search  Healthcare        USA        69277
391  2024-01-03    Meta Ads         Video      EdTech      India       149375
915  2024-01-04    Meta Ads      Shopping  Healthcare     Canada        91284
192  2024-01-04    Meta Ads      Shopping      EdTech         UK       117217
366  2024-01-04  Google Ads       Display     Fintech         UK        20198
554  2024-01-04    Meta Ads       Display      EdTech      India        97152
1743 2024-01-04  Google Ads       Display  E-commerce        USA        52897
383  2024-01-04    Meta Ads        Search  Healthcare         UK       122897
567  2024-01-04  Google Ads         Video      EdTech    Germany        89730
760  2024-01-04    Meta Ads      Shopping      EdTech         UK       184729
36   2024-01-05  TikTok Ads       Display     Fintech        UAE         6015
1154 2024-01-05    Meta Ads      Shopping  E-commerce        USA       139257
1072 2024-01-05  TikTok Ads         Video      EdTech  Australia        52059
1230 2024-01-05  Google Ads      Shopping  Healthcare        UAE        20091
113  2024-01-05  Google Ads        Search      EdTech         UK        41378
828  2024-01-05  Google Ads         Video        SaaS      India       135223
194  2024-01-05    Meta Ads       Display        SaaS        USA        10939
374  2024-01-05    Meta Ads       Display  E-commerce    Germany        88732
37   2024-01-06    Meta Ads        Search  Healthcare  Australia        17763
1349 2024-01-06    Meta Ads         Video  Healthcare  Australia       131681
1151 2024-01-06  Google Ads         Video  E-commerce         UK       139158
1076 2024-01-07  Google Ads         Video  E-commerce    Germany        25080
768  2024-01-07  Google Ads         Video     Fintech        UAE        32476
168  2024-01-07  Google Ads      Shopping      EdTech        UAE        73803
1273 2024-01-07  Google Ads      Shopping      EdTech        USA        73305
1659 2024-01-07    Meta Ads         Video      EdTech    Germany        94440
1443 2024-01-07  Google Ads         Video  E-commerce         UK        33433
1376 2024-01-07  TikTok Ads        Search  Healthcare         UK       166711
371  2024-01-07    Meta Ads         Video  Healthcare    Germany        98944
92   2024-01-07    Meta Ads      Shopping     Fintech  Australia       182235
96   2024-01-08  TikTok Ads        Search     Fintech         UK       162795
43   2024-01-08  Google Ads       Display      EdTech        USA       132600
41   2024-01-08  Google Ads        Search     Fintech      India        63243
147  2024-01-08    Meta Ads         Video      EdTech         UK       127775
1352 2024-01-09  Google Ads        Search        SaaS  Australia        53544
1693 2024-01-09  Google Ads         Video     Fintech         UK       108510
696  2024-01-09  TikTok Ads        Search  Healthcare    Germany        96310
806  2024-01-10  Google Ads         Video  Healthcare  Australia       131031
1737 2024-01-10    Meta Ads      Shopping      EdTech        USA        62284
1331 2024-01-10    Meta Ads        Search        SaaS         UK       175574
773  2024-01-10    Meta Ads         Video     Fintech  Australia        51698
199  2024-01-10    Meta Ads      Shopping  Healthcare        UAE        73323
133  2024-01-10  Google Ads         Video        SaaS         UK       170268
63   2024-01-11  TikTok Ads         Video  Healthcare    Germany       108145
1611 2024-01-11    Meta Ads      Shopping        SaaS        USA       144993
129  2024-01-11    Meta Ads         Video      EdTech         UK       152977
532  2024-01-11  Google Ads        Search  Healthcare    Germany        48351
1421 2024-01-11  TikTok Ads       Display     Fintech         UK       146587
100  2024-01-12  Google Ads        Search     Fintech      India       124273
417  2024-01-12    Meta Ads         Video  Healthcare         UK        62676
1158 2024-01-12    Meta Ads       Display      EdTech     Canada       182011
759  2024-01-12    Meta Ads         Video        SaaS  Australia       176250
34   2024-01-12    Meta Ads         Video  E-commerce     Canada       104657
244  2024-01-13    Meta Ads      Shopping        SaaS      India        24404
1379 2024-01-13  TikTok Ads      Shopping        SaaS      India        83871
1160 2024-01-13    Meta Ads         Video  E-commerce         UK       138686
1643 2024-01-13    Meta Ads       Display  E-commerce         UK        70180
312  2024-01-14  TikTok Ads        Search        SaaS      India        85428
619  2024-01-14    Meta Ads       Display      EdTech      India       171020
433  2024-01-15  Google Ads        Search        SaaS     Canada        43098
701  2024-01-15  Google Ads       Display     Fintech     Canada        55406
940  2024-01-15  Google Ads       Display  E-commerce         UK        62320
807  2024-01-15    Meta Ads        Search      EdTech    Germany       113269
1013 2024-01-15  Google Ads        Search  E-commerce      India        91348
727  2024-01-16    Meta Ads      Shopping  E-commerce         UK       167893
1771 2024-01-16  TikTok Ads         Video  E-commerce  Australia        62868
318  2024-01-16    Meta Ads         Video     Fintech        USA       143421
618  2024-01-16  Google Ads      Shopping        SaaS        UAE        31783
1236 2024-01-16  TikTok Ads      Shopping        SaaS    Germany        88940
861  2024-01-16  TikTok Ads      Shopping        SaaS  Australia        55701
958  2024-01-16  Google Ads        Search      EdTech    Germany       192593
761  2024-01-16  Google Ads        Search  Healthcare         UK       175381
763  2024-01-17    Meta Ads      Shopping  E-commerce    Germany        62033
1313 2024-01-17  Google Ads      Shopping     Fintech         UK       100552
1210 2024-01-17    Meta Ads      Shopping  Healthcare     Canada       185750
1142 2024-01-17    Meta Ads        Search      EdTech  Australia       100343
1651 2024-01-17  TikTok Ads        Search        SaaS     Canada       115716
302  2024-01-17  TikTok Ads         Video      EdTech        UAE       188846
200  2024-01-17  TikTok Ads         Video        SaaS      India        58521
796  2024-01-17  Google Ads         Video     Fintech     Canada        49109
1136 2024-01-17    Meta Ads         Video      EdTech    Germany       190928
426  2024-01-18  Google Ads       Display  E-commerce  Australia        55248
1046 2024-01-18  TikTok Ads         Video      EdTech         UK       172820
1240 2024-01-18  TikTok Ads        Search  E-commerce      India       168616
591  2024-01-18    Meta Ads      Shopping  Healthcare        UAE        84830
1393 2024-01-18    Meta Ads         Video     Fintech     Canada        84712
1396 2024-01-18    Meta Ads         Video     Fintech         UK        72278
334  2024-01-18  Google Ads      Shopping  E-commerce        UAE        76792
1739 2024-01-19  Google Ads        Search  Healthcare        UAE        82764
1658 2024-01-19    Meta Ads      Shopping  Healthcare        USA       173292
112  2024-01-19    Meta Ads         Video      EdTech      India        43467
779  2024-01-19  Google Ads      Shopping     Fintech         UK        55075
1539 2024-01-19  TikTok Ads        Search  E-commerce        USA       179561
479  2024-01-20  Google Ads       Display  E-commerce     Canada       181687
1719 2024-01-20  TikTok Ads         Video     Fintech        USA       153145
134  2024-01-20  Google Ads       Display  Healthcare        USA       122322
583  2024-01-20    Meta Ads      Shopping  Healthcare         UK       147897
1159 2024-01-20  TikTok Ads       Display     Fintech      India        29180
0    2024-01-21  Google Ads        Search     Fintech        UAE        59886
887  2024-01-21    Meta Ads       Display  E-commerce    Germany       161646
923  2024-01-21  Google Ads       Display      EdTech  Australia       186465
1561 2024-01-21  Google Ads       Display  Healthcare  Australia       154239
564  2024-01-21  TikTok Ads       Display        SaaS    Germany        92273
905  2024-01-21  TikTok Ads        Search  Healthcare     Canada       160522
899  2024-01-21  TikTok Ads      Shopping      EdTech        UAE       119944
131  2024-01-22  Google Ads      Shopping     Fintech        USA        28387
1492 2024-01-22  TikTok Ads       Display  Healthcare     Canada       120409
1548 2024-01-22  Google Ads      Shopping     Fintech  Australia       153953
289  2024-01-22  Google Ads       Display      EdTech        UAE        85077
1721 2024-01-22  TikTok Ads      Shopping     Fintech    Germany         5059
1389 2024-01-22    Meta Ads        Search     Fintech        USA        80507
1043 2024-01-22    Meta Ads       Display  Healthcare        USA       197882
1    2024-01-22  TikTok Ads        Search      EdTech         UK       135608
185  2024-01-23    Meta Ads      Shopping        SaaS  Australia        90716
723  2024-01-23  Google Ads        Search  Healthcare      India        57979
1726 2024-01-23  Google Ads        Search     Fintech    Germany         7948
1050 2024-01-24    Meta Ads        Search  Healthcare      India       191478
1425 2024-01-24  TikTok Ads      Shopping        SaaS    Germany       107262
620  2024-01-24  Google Ads      Shopping     Fintech  Australia        31325
811  2024-01-24  TikTok Ads      Shopping      EdTech         UK        79967
119  2024-01-25  Google Ads         Video     Fintech        USA       184316
734  2024-01-25  Google Ads        Search  E-commerce  Australia        92185
1676 2024-01-25  Google Ads        Search      EdTech    Germany       122959
1173 2024-01-25    Meta Ads        Search  Healthcare      India        27499
311  2024-01-25  Google Ads        Search  Healthcare        UAE        50203
512  2024-01-25  TikTok Ads        Search  E-commerce      India        46420
358  2024-01-25  TikTok Ads       Display        SaaS         UK        42706
146  2024-01-26  TikTok Ads      Shopping        SaaS    Germany        34118
799  2024-01-26    Meta Ads        Search  Healthcare        USA       177593
900  2024-01-27  TikTok Ads        Search  Healthcare     Canada        69198
1697 2024-01-27  Google Ads        Search     Fintech      India        79432
369  2024-01-27    Meta Ads       Display  E-commerce  Australia       176459
1390 2024-01-27    Meta Ads        Search     Fintech     Canada       128556
1556 2024-01-27  Google Ads       Display  Healthcare         UK        86362
688  2024-01-27  Google Ads        Search      EdTech        UAE       143183
642  2024-01-27  TikTok Ads         Video        SaaS        UAE       196889
1153 2024-01-27    Meta Ads        Search  E-commerce  Australia        30123
1384 2024-01-28  TikTok Ads       Display  Healthcare      India       104626
127  2024-01-28  Google Ads         Video     Fintech  Australia       193978
1183 2024-01-28    Meta Ads        Search      EdTech        UAE       113878
1012 2024-01-28  Google Ads       Display  E-commerce  Australia        38005
1559 2024-01-28    Meta Ads       Display  Healthcare     Canada        93966
237  2024-01-28  TikTok Ads      Shopping      EdTech        USA        34063
1799 2024-01-29    Meta Ads       Display      EdTech         UK        77447
1506 2024-01-29    Meta Ads        Search     Fintech         UK        56534
425  2024-01-29  Google Ads         Video     Fintech         UK        82462
307  2024-01-29  Google Ads         Video        SaaS    Germany        16781
971  2024-01-29  Google Ads       Display      EdTech        USA       168471
1149 2024-01-30  Google Ads       Display      EdTech        USA        44435
1669 2024-01-30  Google Ads        Search     Fintech     Canada       187156
626  2024-01-30  TikTok Ads         Video     Fintech      India        48147
881  2024-01-30    Meta Ads         Video  Healthcare  Australia        57776
1191 2024-01-30    Meta Ads       Display     Fintech        UAE       166155
1463 2024-01-30  Google Ads         Video        SaaS  Australia        89052
1110 2024-01-31    Meta Ads        Search     Fintech         UK       153157
769  2024-01-31  Google Ads       Display     Fintech     Canada        64739
695  2024-01-31  TikTok Ads      Shopping     Fintech        UAE       127790
967  2024-01-31  TikTok Ads      Shopping        SaaS      India       174668
834  2024-02-01    Meta Ads        Search  E-commerce         UK        63528
1015 2024-02-01  TikTok Ads      Shopping     Fintech      India        95288
405  2024-02-01  Google Ads        Search        SaaS         UK        73681
662  2024-02-01  TikTok Ads         Video  Healthcare  Australia       184504
343  2024-02-01    Meta Ads         Video      EdTech        USA        65942
362  2024-02-01  Google Ads         Video      EdTech        USA        48790
1661 2024-02-02  TikTok Ads         Video  E-commerce        USA       112294
1752 2024-02-02  TikTok Ads      Shopping  Healthcare  Australia       196605
1081 2024-02-02  Google Ads      Shopping  Healthcare        UAE       149848
1054 2024-02-02  Google Ads       Display  E-commerce        USA        65530
1749 2024-02-02  Google Ads         Video        SaaS     Canada        44420
1794 2024-02-03    Meta Ads       Display      EdTech  Australia        76095
636  2024-02-03    Meta Ads      Shopping      EdTech         UK        48271
1311 2024-02-03  TikTok Ads       Display  Healthcare        USA       150227
1438 2024-02-03  TikTok Ads      Shopping  Healthcare  Australia        23043
678  2024-02-04    Meta Ads       Display  Healthcare  Australia       124004
681  2024-02-04  Google Ads        Search        SaaS        USA       137290
1145 2024-02-04  Google Ads        Search      EdTech        UAE       167198
1319 2024-02-04    Meta Ads      Shopping  E-commerce    Germany        82665
679  2024-02-05  TikTok Ads        Search  E-commerce         UK       168322
1276 2024-02-05  Google Ads      Shopping      EdTech        USA        12045
1278 2024-02-05  TikTok Ads      Shopping     Fintech         UK        90443
325  2024-02-05  TikTok Ads         Video        SaaS         UK       123680
1654 2024-02-05    Meta Ads         Video        SaaS      India       145510
1298 2024-02-06    Meta Ads       Display  Healthcare         UK        58164
703  2024-02-06  Google Ads         Video      EdTech         UK        73591
1367 2024-02-06  Google Ads       Display  Healthcare        USA        51678
1021 2024-02-06  Google Ads       Display  E-commerce        UAE        79525
1116 2024-02-06    Meta Ads         Video  E-commerce        UAE        92469
1545 2024-02-06  TikTok Ads         Video  E-commerce     Canada        48475
1091 2024-02-06  Google Ads      Shopping  E-commerce    Germany       102409
1064 2024-02-06  TikTok Ads       Display        SaaS  Australia        53709
804  2024-02-06    Meta Ads       Display      EdTech      India       184541
159  2024-02-07    Meta Ads      Shopping  Healthcare     Canada       101019
135  2024-02-07    Meta Ads       Display  Healthcare         UK        69429
1579 2024-02-07  TikTok Ads       Display     Fintech    Germany       103029
1764 2024-02-07  TikTok Ads        Search     Fintech    Germany       108806
927  2024-02-07  Google Ads        Search     Fintech    Germany       163349
1330 2024-02-07  Google Ads       Display  E-commerce    Germany        96931
248  2024-02-08    Meta Ads        Search      EdTech         UK       151480
1665 2024-02-08  TikTok Ads       Display     Fintech    Germany       113994
1338 2024-02-08  TikTok Ads        Search      EdTech        USA       128900
466  2024-02-08  Google Ads      Shopping        SaaS         UK        10574
1238 2024-02-08  TikTok Ads        Search  Healthcare      India        17911
543  2024-02-09    Meta Ads         Video  E-commerce      India       170413
1497 2024-02-10  TikTok Ads      Shopping        SaaS        USA       116709
524  2024-02-10    Meta Ads         Video  Healthcare         UK       141313
1059 2024-02-10  Google Ads      Shopping  E-commerce        UAE        24198
562  2024-02-10  Google Ads      Shopping  Healthcare  Australia       167717
644  2024-02-11  Google Ads      Shopping     Fintech        UAE        29016
1083 2024-02-11  TikTok Ads         Video      EdTech      India       157625
1138 2024-02-11    Meta Ads         Video        SaaS        UAE        92986
1128 2024-02-11  Google Ads        Search        SaaS         UK       137156
643  2024-02-11  TikTok Ads       Display      EdTech         UK        77467
970  2024-02-12  TikTok Ads       Display  Healthcare        UAE        74285
1628 2024-02-12  TikTok Ads         Video     Fintech        USA        41497
1169 2024-02-13    Meta Ads         Video  E-commerce      India        57299
1095 2024-02-13  Google Ads        Search        SaaS  Australia       153865
1778 2024-02-13  Google Ads         Video  E-commerce         UK        48766
505  2024-02-13  Google Ads        Search  E-commerce    Germany       188276
81   2024-02-14  TikTok Ads         Video  Healthcare     Canada        79553
1065 2024-02-14  Google Ads       Display  Healthcare         UK        25497
382  2024-02-14    Meta Ads         Video        SaaS      India        83137
909  2024-02-15    Meta Ads       Display      EdTech    Germany        67167
743  2024-02-15  Google Ads        Search     Fintech    Germany        30835
293  2024-02-15  Google Ads      Shopping     Fintech    Germany        39754
1627 2024-02-16  Google Ads         Video  Healthcare  Australia        83702
1524 2024-02-16    Meta Ads         Video      EdTech         UK       165408
716  2024-02-16    Meta Ads      Shopping     Fintech     Canada        35755
965  2024-02-16  Google Ads       Display      EdTech     Canada       197974
774  2024-02-16  Google Ads      Shopping        SaaS        UAE        50206
702  2024-02-16  TikTok Ads       Display     Fintech  Australia       141447
1666 2024-02-16  Google Ads        Search      EdTech        UAE        90794
1123 2024-02-16    Meta Ads      Shopping     Fintech        USA       178553
1176 2024-02-16    Meta Ads         Video  Healthcare     Canada       133088
1418 2024-02-16  Google Ads         Video  E-commerce    Germany       180069
1441 2024-02-16    Meta Ads      Shopping     Fintech      India        19040
952  2024-02-17    Meta Ads       Display     Fintech    Germany       104926
698  2024-02-17    Meta Ads         Video  E-commerce        USA       118566
196  2024-02-17  Google Ads      Shopping     Fintech    Germany        78402
328  2024-02-17    Meta Ads         Video  E-commerce     Canada       150631
476  2024-02-17  Google Ads         Video        SaaS    Germany       133027
176  2024-02-17  TikTok Ads      Shopping  Healthcare     Canada       130438
125  2024-02-17  Google Ads        Search        SaaS    Germany       142244
1272 2024-02-17  Google Ads         Video        SaaS     Canada       150213
838  2024-02-17  Google Ads         Video     Fintech        UAE        15046
277  2024-02-17  TikTok Ads        Search     Fintech    Germany       113297
241  2024-02-17    Meta Ads         Video  E-commerce    Germany        16094
857  2024-02-18    Meta Ads        Search        SaaS        UAE       161738

In [27]:
print(df.duplicated().sum())

0